name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ env.DOCKER_MANIFEST == '' || github.event_name == 'push' }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ env.DOCKER_MANIFEST == '' || github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ env.DOCKER_MANIFEST == '' || github.event_name == 'push' }}
        with:
          push: true
          tags: laravelfans/ping:latest

      - name: Image digest
        if: steps.docker_build.conclusion == 'success'
        run: echo ${{ steps.docker_build.outputs.digest }}
